[project]
name = "RealBit"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.realbit-marketplace]
path = "contracts/realbit-marketplace.clar"
depends_on = []

[contracts.realbit-property]
path = "contracts/realbit-property.clar"
depends_on = []

[contracts.realbit-shares]
path = "contracts/realbit-shares.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
